services:
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./var-lib-letsencrypt:/var/lib/letsencrypt
      - ./var-log-letsencrypt:/var/log/letsencrypt

